<?php 
    $this->headTitle('Phone - New Message');
//    $this->headMeta()->appendName('keywords', "zend framework, zend, angularJS, web framework, cms, phone, content management system, users, user admin, module, modular, zend module");
?>

<div class="container-fluid">
    <div class="form-phone">
        <div class="navbar navbar-btn navbar-right">
            <h4>
                <small>
                    <a href="<?php echo $this->url('phone'); ?>"><i class="fa fa-times"> Cancel</i></a>
                </small>            
            </h4>
        </div>
        <div class="row-fluid">
            <h3>Create Message</h3>
            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="To: <?php // echo "<small>Separate by comma (,) for multiple numbers</small>"; ?>" data-toggle="tooltip" data-placement="left" title="Separate by comma (,) for multiple numbers"/>
                </div>
                <div class="form-group">
                    <textarea class="form-control" rows="5" placeholder="Message:"></textarea>
                </div>
                <div class="btn-toolbar">
                    <button type="submit" class="btn btn-primary btn-block"> <i class="fa fa-share-square-o"> Send</i> </button>
                </div>
            </form>
        </div>
    </div>
</div>