<?php 
    $this->headTitle('Phone - New Message');
//    $this->headMeta()->appendName('keywords', "zend framework, zend, angularJS, web framework, cms, phone, content management system, users, user admin, module, modular, zend module");
?>

<div class="container-fluid">
    <div class="form-phone">
        <div class="navbar navbar-btn navbar-right">
            <h4>
                <small>
                    <a href="<?php echo $this->url('phone'); ?>"><i class="fa fa-times"> Cancel</i></a>
                </small>            
            </h4>
        </div>
        <div class="row-fluid">
            <h3>Create Message</h3>
            <form>
                <div class="form-group"></div>
            </form>
        </div>
    </div>
</div>