<?php 
    $this->headTitle('Phone - New Message');
//    $this->headMeta()->appendName('keywords', "zend framework, zend, angularJS, web framework, cms, phone, content management system, users, user admin, module, modular, zend module");
?>

<div class="container-fluid">
    <div class="form-phone">
        <div class="navbar navbar-btn">
            <div class="navbar-left">
                <h4> 
                    <small>
                        <a href="<?php echo $this->url('phone/inbox'); ?>"><i class="fa fa-backward"> Back</i></a>                   
                    </small>
                </h4>
            </div>
            <div class="navbar-right">
                <h4>
                    <small>
                        <!--<a href="<?php echo $this->url('phone/reply', ['number'=> 'new']); ?>"><i class="fa fa-mail-reply"> Reply</i></a>-->
                    </small>
                </h4>
            </div>
        </div>
        <div class="row-fluid">
            <h3><?php echo $this->sms['sender_name'];?> <small><?php echo $this->sms['contact_number']?></small></h3>
            <textarea class="form-control" rows="3" disabled placeholder="<?php echo $this->sms['message'];?>"></textarea>
        </div>
    </div>
</div>